import os
import rtconfig
from building import *

cwd = GetCurrentDir()
drv_path = cwd+"/../../../rt-thread/bsp/k210/driver/"
src     = [
    'board.c',
    'heap.c',
    drv_path + 'drv_uart.c',
    'drv_interrupt.c',
    'drv_io_config.c',
    'dmalock.c'
]
CPPPATH = [cwd,drv_path]

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

if GetDepend('RT_USING_HWTIMER'):
    src += [drv_path + 'drv_hw_timer.c']
    
if GetDepend('RT_USING_I2C'):
    src += ['drv_hw_i2c.c']

if GetDepend('RT_USING_TOUCH'): 
    src += ['drv_gt911_touch.c']  

if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']
if GetDepend('RT_USING_PWM'):
    src += [drv_path + 'drv_pwm.c']
if GetDepend('RT_USING_WDT'):
    src += [drv_path + 'drv_wdt.c']

if GetDepend('BSP_USING_LCD'):
    src += ['drv_lcd.c']
    src += ['drv_mpylcd.c']
    src += ['drv_lt768_lcd.c']
    src += ['LT768_Lib.c']
    src += ['LT768.c']

if GetDepend('BSP_USING_CH376'):
    src += ['ch376.c']
    src += ['ch376_fs.c']

if GetDepend('BSP_USING_CH438'):
    src += ['ch438.c']
    
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
