from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
MCUX_Config/clock_config.c
MCUX_Config/pin_mux.c
""")

CPPPATH = [cwd,cwd + '/MCUX_Config',cwd + '/ports',cwd + '/usb']
CPPDEFINES = ['CPU_MIMXRT1052CVL5B', 'SKIP_SYSCLK_INIT', 'EVK_MCIMXRM', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1','XIP_EXTERNAL_FLASH=1']
if GetDepend('BSP_USING_PHY') and GetDepend('PHY_USING_8720A'):
    src += ['./ports/LAN8720A.c']
if GetDepend('BSP_USING_SDCARD'):
    src += ['./ports/sdcard_port.c']
if GetDepend(['RT_USING_DFS_ROMFS']):
    src += ['ports/romfs.c']
    src += ['ports/mnt_romfs.c']
if GetDepend('RT_USING_USB_HOST'):
    src += ['usb/drv_usbh.c']
if GetDepend('BSP_USING_LCD_XIDATONG'):
    src += ['ports/ok1052lcd.c']
    src += ['ports/drv_lcd.c']
    src += ['../../../../rt-thread/bsp/imxrt/libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_elcdif.c']
if GetDepend('BSP_USING_I2C1'):
    src += ['ports/touch.c']
    src += ['ports/drv_touch.c']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
