from building import *

cwd     = GetCurrentDir()
src     = [
    'main.c'
]
CPPPATH = [cwd]

if GetDepend('BSP_USING_LCD'):
    src += ['lcd_test.c']
    src += ['lcd_lt768_test.c']
    
if GetDepend('PKG_USING_WIZNET'):
    src += ['tcp_client.c']
    src += ['tcp_server.c']

if GetDepend('RT_USING_TOUCH'): 
    src += ['touch_gt911_test.c'] 
    
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')



