import os
from building import * 
Import('RTT_ROOT')
Import('rtconfig')
cwd = GetCurrentDir()
DEPENDS = ["LIB_LV"]
SOURCES = []
SOURCES = ['lv_init.c'] + ['lv_demo.c']+['lv_demo_calendar.c']
path =  [cwd]
objs = DefineGroup('sensor_app', src = SOURCES, depend = DEPENDS,CPPPATH = path) 
Return("objs") 