import os
import rtconfig
from building import *

cwd = GetCurrentDir()
src     = [
    'main.c',
    'rt_client.c',
    'test_485.c',
    'test_232.c',
    'can_test.c'
]
CPPPATH = [cwd]

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    CPPDEFINES = ['__START=entry']
else:
    CPPDEFINES = []
    
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
